[pytest]
testpaths = tests
python_files = test_*.py
# --headed дозволить бачити браузер, --slowmo додасть затримку для наочності
addopts = -v --tb=short --slowmo 500

# Налаштування формату логів
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s (%(filename)s:%(lineno)s)
log_cli_date_format = %d-%m-%Y %H:%M:%S
